### ISSUE TITLE
Ruta local en HashCodeMain

### ISSUE THREAD

**Issue by fjlopez** [Carmot/HashCode2017_Pastutatis#1]
En la clase [HashCodeMain](https://github.com/Carmot/HashCode2017_Pastutatis/blob/master/HashCodeMain.java#L28) está la siguiente sentencia:

```java
Path path = FileSystems.getDefault().getPath("/Users/joseangelgariburo/hashcode2017/src/Resources/" + fileNameSmall, "");
```

Tal como está el código subido debería ser 

```java
Path path = Paths.getPath(args[0]);
```

Resuelve dos problemas:
- `fileNameSmall` es una constante actualmente
- la ruta de ejecución ya no está codificada en el código fuente

**Comment by JorgeCanellas** [comment]
Buenas!
Lo modificamos en una rama posterior, quedó algo similar a este [gist](https://gist.github.com/JorgeCanellas/fbec5157c57ad49ab7b238349b30e4db)
